# Generated by Django 5.1.2 on 2024-11-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.DateField()),
                ('nomor_isbn', models.CharField(max_length=100)),
                ('judul_buku', models.CharField(max_length=100)),
                ('jumlah_buku', models.IntegerField()),
                ('status_buku', models.CharField(choices=[('T', 'Tersedia'), ('D', 'Dipinjam'), ('R', 'Reservasi')], max_length=30)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jenis_anggota', models.CharField(choices=[('M', 'Mahasiswa'), ('D', 'Dosen'), ('U', 'Umum')], max_length=30)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_peminjaman', models.DateField()),
                ('batas_peminjaman', models.DateTimeField()),
                ('status_peminjaman', models.CharField(choices=[('P', 'Dipinjam'), ('K', 'DiKembalikam')], max_length=30)),
                ('id_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_buku', to='perpusApp.buku')),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_member', to='perpusApp.member')),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
        migrations.CreateModel(
            name='pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pengembalian', models.DateField()),
                ('status_pengembalian', models.CharField(choices=[('D', 'Dikembalikan'), ('T', 'Terlambat')], max_length=30)),
                ('id_peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_peminjaman', to='perpusApp.peminjaman')),
            ],
            options={
                'db_table': 'pengembalian',
            },
        ),
        migrations.CreateModel(
            name='denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_hari', models.IntegerField()),
                ('tgl_denda', models.DateField()),
                ('jml_denda', models.IntegerField()),
                ('status_denda', models.CharField(choices=[('L', 'Lunas'), ('B', 'Belum Lunas')], max_length=30)),
                ('id_peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_peminjaman_denda', to='perpusApp.peminjaman')),
                ('id_pengembalian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pengembalian_denda', to='perpusApp.pengembalian')),
            ],
            options={
                'db_table': 'denda',
            },
        ),
        migrations.CreateModel(
            name='reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_reservasi', models.DateField()),
                ('tgl_pengembalian', models.DateField()),
                ('status_reservasi', models.CharField(choices=[('A', 'Aktif'), ('C', 'Dibatalkan'), ('S', 'Selesai')], max_length=30)),
                ('id_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_buku_reservasi', to='perpusApp.buku')),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_member_reservasi', to='perpusApp.member')),
            ],
            options={
                'db_table': 'reservasi',
            },
        ),
    ]
