# Generated by Django 5.1.2 on 2024-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='jenis_anggota',
            field=models.CharField(choices=[('M', 'Mahasiswa'), ('D', 'Dosen'), ('U', 'Umum')], default='U', max_length=30),
        ),
    ]
